import {indicatorCatalog,normalizeStudy} from './chart-indicators.js';
import {drawingGroups,drawingStyle} from './chart-tool-catalog.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function initTerminalEditors({panel,preferences,activeChart,activeDoc,openInstrument,getCatalog,compare,plan,alert,loadHistory,jumpDate,showToast}) {
 const popup=document.createElement('section');popup.className='terminal-popover';popup.hidden=true;popup.setAttribute('role','dialog');panel.append(popup);
 let returnFocus=null;
 function close(restoreFocus=true){returnFocus?.hasAttribute?.('aria-expanded')&&returnFocus.setAttribute('aria-expanded','false');popup.hidden=true;delete popup.dataset.editing;if(restoreFocus)returnFocus?.focus?.({preventScroll:true});returnFocus=null;}
 function show(anchor,title,html){popup.onsubmit=null;delete popup.dataset.editing;returnFocus?.hasAttribute?.('aria-expanded')&&returnFocus.setAttribute('aria-expanded','false');returnFocus=anchor?.focus?anchor:document.activeElement;returnFocus?.hasAttribute?.('aria-expanded')&&returnFocus.setAttribute('aria-expanded','true');popup.setAttribute('aria-label',title);popup.innerHTML=`<header><strong>${esc(title)}</strong><button type="button" data-popup-close aria-label="Закрыть">×</button></header>${html}`;popup.hidden=false;
  const rect=anchor?.getBoundingClientRect?.()||{left:anchor?.clientX||24,bottom:anchor?.clientY||64};
  popup.style.left=Math.max(8,Math.min(innerWidth-popup.offsetWidth-8,rect.left))+'px';popup.style.top=Math.max(8,Math.min(innerHeight-popup.offsetHeight-8,rect.bottom+6))+'px';popup.querySelector('input,button')?.focus({preventScroll:true});
 }
 popup.addEventListener('click',e=>{if(e.target.closest('[data-popup-close]'))close();});
 document.addEventListener('pointerdown',e=>{if(!popup.hidden&&!popup.contains(e.target)&&!returnFocus?.contains?.(e.target)){close(false);}},true);
 popup.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}});
 const api=()=>activeChart()?.api;
 function indicators(anchor){
  const studies=()=>api()?.getState().studies||[];
  const row=s=>`<div class="terminal-study-row" data-study="${esc(s.id)}"><label><input type="checkbox" data-study-field="visible" ${s.visible?'checked':''}>${esc(s.type.toUpperCase())}</label><label>Период<input type="number" min="1" max="500" value="${s.period}" data-study-field="period"></label><label>Цвет<input type="color" value="${s.color}" data-study-field="color"></label>${s.type==='macd'?`<label>Быстрая<input type="number" min="1" max="499" value="${s.fast}" data-study-field="fast"></label><label>Сигнал<input type="number" min="1" max="100" value="${s.signal}" data-study-field="signal"></label>`:''}${['bb','keltner'].includes(s.type)?`<label>Множитель<input type="number" min=".1" max="10" step=".1" value="${s.deviations}" data-study-field="deviations"></label>`:''}<button type="button" data-remove-study aria-label="Удалить ${esc(s.type)}">×</button></div>`;
  show(anchor,'Индикаторы',`<input class="terminal-picker-search" type="search" aria-label="Найти индикатор" placeholder="Название индикатора"><div class="terminal-study-presets">EMA: ${[20,50,120,200].map(p=>`<button type="button" data-preset="${p}">${p}</button>`).join('')}</div><div class="terminal-study-current"></div><div class="terminal-study-catalog">${indicatorCatalog.map(d=>`<button type="button" data-add-study="${d.type}">${esc(d.label)}</button>`).join('')}</div><p class="terminal-caption">Периоды прогрева не заполняются вымышленными значениями. На одном графике — до 24 индикаторов.</p>`);
  const render=()=>popup.querySelector('.terminal-study-current').innerHTML=studies().map(row).join('');render();
  popup.querySelector('[type=search]').addEventListener('input',e=>{for(const b of popup.querySelectorAll('[data-add-study]'))b.hidden=!b.textContent.toLowerCase().includes(e.target.value.toLowerCase());});
  const add=(type,period)=>{if(studies().length>=24){showToast('На графике уже 24 индикатора.');return;}api()?.setStudies([...studies(),normalizeStudy({id:'study-'+crypto.randomUUID(),type,period,color:getComputedStyle(document.documentElement).getPropertyValue('--vertux-soft').trim()})]);render();};
  popup.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-popup-close'))close();else if(b.dataset.addStudy)add(b.dataset.addStudy);else if(b.dataset.preset)add('ema',Number(b.dataset.preset));else if(b.hasAttribute('data-remove-study')){api()?.setStudies(studies().filter(s=>s.id!==b.closest('[data-study]').dataset.study));render();}};
  popup.onchange=e=>{const field=e.target.dataset.studyField,id=e.target.closest('[data-study]')?.dataset.study;if(!field||!id)return;const value=field==='visible'?e.target.checked:field==='color'?e.target.value:Number(e.target.value);api()?.setStudies(studies().map(s=>s.id===id?{...s,[field]:value}:s));const current=studies().find(s=>s.id===id);if(current)for(const input of e.target.closest('[data-study]').querySelectorAll('[data-study-field]')){if(input.type==='checkbox')input.checked=current[input.dataset.studyField];else input.value=current[input.dataset.studyField];}};
 }
 function datePicker(anchor){
  const doc=activeDoc(),today=new Date().toISOString().slice(0,10);popup.onclick=null;popup.onchange=null;
  show(anchor,'Перейти к истории',`<form class="terminal-date-form"><label>Дата на графике<input name="chartDate" type="date" min="1970-01-01" max="${today}" value="${doc?.historyDate||today}" required></label><button class="button primary" type="submit">Перейти</button></form><div class="terminal-year-shortcuts">${[2018,2021,2022,2024,new Date().getFullYear()].map(y=>`<button type="button" data-chart-year="${y}">${y}</button>`).join('')}</div><p class="terminal-caption">Загружается архив выбранного инструмента. Его начало зависит от источника и интервала свечей.</p><p class="terminal-date-result" role="status"></p>`);
  const go=async(date,year=false)=>{const status=popup.querySelector('.terminal-date-result');status.textContent='Загружаем архив…';for(const b of popup.querySelectorAll('button:not([data-popup-close])'))b.disabled=true;
   try{await jumpDate(date,year);if(popup.contains(status))close();}catch(e){if(popup.contains(status)){status.textContent=e.message||'История не загрузилась. Повторите.';for(const b of popup.querySelectorAll('button'))b.disabled=false;}}
  };
  popup.onsubmit=e=>{e.preventDefault();void go(new FormData(e.target).get('chartDate'));};
  popup.onclick=e=>{const year=e.target.closest('[data-chart-year]')?.dataset.chartYear;if(year)void go(Number(year)===new Date().getFullYear()?today:year+'-07-01',true);};
 }
 function scale(anchor){
  const state=api()?.getState()||{};popup.onclick=null;popup.onchange=null;
  show(anchor,'Шкала графика',`<div class="terminal-scale-options"><label>Отображение<select name="scaleMode">${[['normal','Обычная цена'],['log','Логарифмическая'],['percent','Изменение, %'],['indexed','Индекс от 100']].map(([v,t])=>`<option value="${v}" ${state.scaleMode===v?'selected':''}>${t}</option>`).join('')}</select></label><label><input type="checkbox" name="inverted" ${state.inverted?'checked':''}>Инвертировать шкалу</label><label><input type="checkbox" name="magnet" ${state.magnet?'checked':''}>Магнит к OHLC свечи</label></div><p class="terminal-caption">Магнит привязывает точки к ближайшей свече и её цене открытия, максимуму, минимуму или закрытию. При сравнении используется общая процентная шкала.</p>`);
  popup.onchange=e=>{if(e.target.name==='magnet')api()?.drawings.setMagnet(e.target.checked);else api()?.setScale(popup.querySelector('[name=scaleMode]').value,popup.querySelector('[name=inverted]').checked);};
 }
 function objects(anchor){
  popup.onclick=null;popup.onchange=null;
  show(anchor,'Объекты графика','<div class="terminal-object-list"></div><p class="terminal-caption">Выберите свойства объекта, скройте его или закрепите от случайного перемещения.</p>');popup.dataset.editing='objects';
  const names=new Map(drawingGroups.flatMap(g=>g.tools));
  const render=()=>{const items=api()?.drawings.getState()||[];popup.querySelector('.terminal-object-list').innerHTML=items.length?items.map(d=>`<div class="terminal-object-row" data-object-id="${esc(d.id)}"><button type="button" data-object-action="edit">${esc(names.get(d.type)||d.type)}</button><button type="button" data-object-action="hidden" aria-pressed="${!!d.hidden}" aria-label="Скрыть ${esc(names.get(d.type))}">${d.hidden?'Показать':'Скрыть'}</button><button type="button" data-object-action="locked" aria-pressed="${!!d.locked}">${d.locked?'Открепить':'Закрепить'}</button><button type="button" data-object-action="delete" aria-label="Удалить ${esc(names.get(d.type))}">×</button></div>`).join(''):'<p class="empty-copy">Рисунков пока нет. Выберите инструмент на левой панели графика.</p>';};render();
  popup.onclick=e=>{const b=e.target.closest('[data-object-action]');if(!b)return;const layer=api()?.drawings;layer?.select(b.closest('[data-object-id]').dataset.objectId);const item=layer?.getSelected();if(!item)return;
   if(b.dataset.objectAction==='edit'){drawing(item);return;}if(b.dataset.objectAction==='delete')layer.deleteSelected();else layer.editSelected({[b.dataset.objectAction]:!item[b.dataset.objectAction]});render();};
 }
 function picker(anchor,comparison=false){show(anchor,comparison?'Сравнить инструменты':'Найти инструмент',`<input class="terminal-picker-search" type="search" aria-label="Тикер или название" placeholder="Тикер или название"><div class="terminal-compare-current"></div><div class="terminal-symbol-results"></div>${comparison?'<p class="terminal-caption">Изменение цен на общей процентной шкале, от первой общей свечи. Валюты не конвертируются.</p>':''}`);
  const current=()=>{popup.querySelector('.terminal-compare-current').innerHTML=(comparison?activeDoc()?.comparisons||[]:[]).map(m=>`<button type="button" data-remove-compare="${esc(m.instrumentUid)}">${esc(m.ticker)} ×</button>`).join('');};current();
  const render=q=>{const matches=getCatalog().filter(m=>(m.ticker+' '+m.name).toLowerCase().includes(q.toLowerCase())).slice(0,60);popup.querySelector('.terminal-symbol-results').innerHTML=matches.length?matches.map(m=>`<button type="button" data-symbol="${esc(m.instrumentUid)}"><strong>${esc(m.ticker)}</strong><span>${esc(m.name)}</span></button>`).join(''):'<p>Инструмент не найден.</p>';};render('');
  popup.querySelector('[type=search]').addEventListener('input',e=>render(e.target.value));
  popup.onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-popup-close'))close();else if(b.dataset.symbol){const m=getCatalog().find(m=>m.instrumentUid===b.dataset.symbol);if(comparison){await compare(m);current();}else{await openInstrument(m);close();}}else if(b.dataset.removeCompare){await compare({instrumentUid:b.dataset.removeCompare},true);current();}};popup.onchange=null;
 }
 function tools(anchor,index){popup.onclick=null;popup.onchange=null;const group=drawingGroups[index];anchor.setAttribute('aria-expanded','true');show(anchor,group.label,group.tools.map(([type,label])=>`<button class="terminal-menu-action" type="button" data-drawing-tool="${type}">${esc(label)}</button>`).join(''));popup.onclick=e=>{const b=e.target.closest('[data-drawing-tool]');if(b){preferences?.chooseTool(b.dataset.drawingTool,index);api()?.beginDrawing(b.dataset.drawingTool);close();}};}
 function settings(anchor){popup.onclick=null;popup.onchange=null;show(anchor,'Настройки графика','<div data-chart-settings></div>');preferences.mount(popup.querySelector('[data-chart-settings]'),{currentChart:api,instrumentUid:()=>activeDoc()?.instrumentUid});}
 function drawing(item){if(!item){if(popup.dataset.editing==='drawing'){popup.hidden=true;delete popup.dataset.editing;}return;}const style=drawingStyle(item.style,item.type);popup.onclick=null;popup.onchange=null;
  show(activeChart()?.card.querySelector('[data-tool=cursor]'),'Свойства рисунка',`<div class="terminal-drawing-properties"><label>Цвет<input type="color" name="color" value="${style.color}"></label><label>Прозрачность<input type="range" name="opacity" min=".05" max="1" step=".05" value="${style.opacity}"></label><label>Толщина<input type="number" name="width" min="1" max="12" step=".5" value="${style.width}"></label><label>Заливка<input type="range" name="fill" min="0" max="1" step=".05" value="${style.fill}"></label><label>Линия<select name="dash">${[['solid','Сплошная'],['dash','Штрих'],['dot','Точки']].map(([v,t])=>`<option value="${v}" ${style.dash===v?'selected':''}>${t}</option>`).join('')}</select></label>${item.type.startsWith('fib')?`<label><input type="checkbox" name="multicolor" ${style.multicolor?'checked':''}>Разноцветные уровни</label><div class="chart-fib-palette wide">${style.levelColors.map((c,i)=>`<label>Уровень ${i+1}<input type="color" name="levelColor${i}" value="${c}"></label>`).join('')}</div><label class="wide">Уровни через пробел<input name="levels" value="${style.levels.join(' ')}"></label><label><input type="checkbox" name="prices" ${style.prices?'checked':''}>Цены уровней</label><label><input type="checkbox" name="extend" ${style.extend?'checked':''}>Продлить вправо</label>`:''}${['text','callout'].includes(item.type)?`<label class="wide">Текст<input name="text" maxlength="300" value="${esc(style.text)}"></label>`:''}<label><input type="checkbox" name="locked" ${item.locked?'checked':''}>Закрепить</label></div><footer><button type="button" data-copy-drawing>Копия</button><button type="button" data-delete-drawing>Удалить</button></footer>`);popup.dataset.editing='drawing';
  if(['fibTime','fibArcs','fibCircles'].includes(item.type))popup.querySelector('[name=prices]').closest('label').remove();
  if(['fibTime','fibFan','fibArcs','fibCircles'].includes(item.type))popup.querySelector('[name=extend]').closest('label').remove();
  popup.onchange=e=>{const name=e.target.name;if(!name)return;const value=name.startsWith('levelColor')?drawingStyle(api()?.drawings.getSelected()?.style,item.type).levelColors.map((c,i)=>i===Number(name.slice(10))?e.target.value:c):name==='levels'?e.target.value.split(/[;\s]+/).filter(Boolean).map(v=>Number(v.replace(',','.'))):e.target.type==='checkbox'?e.target.checked:['opacity','width','fill'].includes(name)?Number(e.target.value):e.target.value;
   // Avoid rebuilding the focused form during a change.
   const selected=api()?.drawings;popup.dataset.editing='updating';selected?.editSelected(name==='locked'?{locked:value}:{style:{[name.startsWith('levelColor')?'levelColors':name]:value}});popup.dataset.editing='drawing';};
  popup.onclick=e=>{if(e.target.closest('[data-delete-drawing]')){api()?.drawings.deleteSelected();close();}if(e.target.closest('[data-copy-drawing]'))api()?.drawings.duplicateSelected();};
 }
 panel.addEventListener('contextmenu',e=>{const host=e.target.closest('.terminal-chart-plot');if(!host)return;e.preventDefault();host.closest('[data-chart-id]').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));const series=api()?.getSeries(),price=series?.coordinateToPrice(e.clientY-host.getBoundingClientRect().top);const object=e.target.closest('[data-drawing-id]');if(object)api()?.drawings.select(object.dataset.drawingId);
  popup.onclick=null;popup.onchange=null;show(e,'Действия с графиком',`<button class="terminal-menu-action" data-context="search">Найти инструмент</button><button class="terminal-menu-action" data-context="compare">Сравнить инструменты</button><button class="terminal-menu-action" data-context="indicators">Индикаторы</button><button class="terminal-menu-action" data-context="fit">Показать весь график</button><button class="terminal-menu-action" data-context="history">Загрузить более раннюю историю</button>${Number.isFinite(price)&&price>0?`<button class="terminal-menu-action" data-context="plan">План от цены ${esc(price.toLocaleString('ru-RU',{maximumFractionDigits:5}))}</button><button class="terminal-menu-action" data-context="alert">Уведомление на эту цену</button>`:''}${object?'<button class="terminal-menu-action" data-context="drawing">Свойства рисунка</button><button class="terminal-menu-action" data-context="delete">Удалить рисунок</button>':''}`);
  popup.onclick=event=>{const action=event.target.closest('[data-context]')?.dataset.context;if(!action)return;popup.hidden=true;if(action==='search')picker(e);if(action==='compare')picker(e,true);if(action==='indicators')indicators(e);if(action==='fit')api()?.fitContent();if(action==='history')loadHistory();if(action==='plan')plan(price);if(action==='alert')alert(price);if(action==='drawing')drawing(api()?.drawings.getSelected());if(action==='delete')api()?.drawings.deleteSelected();};
 });
 return {indicators,picker,tools,settings,datePicker,scale,objects,drawing:item=>{if(!['updating','objects'].includes(popup.dataset.editing))drawing(item);},close};
}
