import {chartTime} from './chart-resolutions.js';
export function initReplayControls({main,button,activeChart,onStop=()=>{}}){
 const bar=document.createElement('section');bar.className='terminal-replay-bar';bar.hidden=true;bar.setAttribute('aria-label','Воспроизведение истории');
 bar.innerHTML='<button type="button" data-replay="pick">Выбрать свечу</button><form class="terminal-replay-date"><label>Дата<input type="date" name="replayDate" required aria-label="Дата начала воспроизведения"></label><button type="submit">Начать</button></form><div class="terminal-replay-actions"><button type="button" data-replay="back" aria-label="Предыдущая свеча">↤</button><button type="button" data-replay="play">Воспроизвести</button><button type="button" data-replay="step" aria-label="Следующая свеча">↦</button><select data-replay-speed aria-label="Скорость воспроизведения">'+[.1,.25,.5,1,2,3,5,7,10,20].map(v=>`<option value="${v}" ${v===1?'selected':''}>${v}×</option>`).join('')+'</select><button type="button" data-replay="close" aria-label="Выйти из воспроизведения">×</button></div><output class="terminal-replay-status" role="status"></output><small>1× = 1 свеча/с · Будущие свечи скрыты. Остальные панели показывают последний снимок.</small>';
 main.querySelector('.terminal-grid').after(bar);let previous=null,picker=null,cleanup=null;
 const api=()=>activeChart()?.api,field=bar.querySelector('[name=replayDate]'),status=bar.querySelector('output'),zone=()=>api()?.getState().timezone||'Europe/Moscow';
 const day=t=>new Intl.DateTimeFormat('en-CA',{timeZone:zone(),year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t*1000));
 function cancelPick(){cleanup?.();cleanup=null;picker?.remove();picker=null;bar.querySelector('[data-replay=pick]').setAttribute('aria-pressed','false');}
 function update(){const current=api(),s=current?.getReplay()||{active:false};button.setAttribute('aria-pressed',String(!bar.hidden));if(s.speed)bar.querySelector('[data-replay-speed]').value=String(s.speed);
  bar.querySelector('[data-replay=play]').textContent=s.playing?'Пауза':'Воспроизвести';for(const action of ['play','step'])bar.querySelector(`[data-replay=${action}]`).disabled=!s.active||s.index>=(s.end??s.total-1);bar.querySelector('[data-replay=back]').disabled=!s.active||s.index===0;
  if(s.active){bar.hidden=false;bar.dataset.time=s.time;bar.dataset.count=s.index+1;status.textContent=chartTime(s.time,zone())+' · '+(s.index+1)+' / '+((s.end??s.total-1)+1)+(s.index===s.end?' · Конец выбранного участка':'');}
  else{delete bar.dataset.time;delete bar.dataset.count;status.textContent=current?'Нажмите на свечу начала. Протяните по графику, чтобы задать конец участка.':'Дождитесь загрузки свечей.';}
  const rows=current?.getSourceRows()||activeChart()?.rows||[];bar.querySelector('[type=submit]').disabled=rows.length<2;if(rows.length){field.min=day(rows[0].time);field.max=day(rows.at(-1).time);if(!field.value||field.value<field.min||field.value>field.max)field.value=day(rows[Math.floor((rows.length-1)*.7)].time);}
 }
 function pick(){cancelPick();const entry=activeChart(),current=entry?.api;if(!current)return;current.stopReplay();current.beginDrawing(null);bar.hidden=false;update();picker=document.createElement('div');picker.className='terminal-replay-picker';picker.tabIndex=0;picker.setAttribute('role','application');picker.setAttribute('aria-label','Выбор начала воспроизведения: нажмите на свечу; стрелки и Enter — с клавиатуры');picker.innerHTML='<div class="replay-future"></div><div class="replay-boundary"></div><span class="replay-pick-label"></span>';entry.host.append(picker);const rows=current.getSourceRows();let start=null,index=Math.floor(rows.length*.7),finish=index;
  function point(e){const x=Math.max(0,Math.min(entry.host.clientWidth-65,e.clientX-entry.host.getBoundingClientRect().left)),logical=current.chart.timeScale().coordinateToLogical(x);return Math.max(0,Math.min(rows.length-1,Math.round(logical??index)));}
  function paint(){const a=Math.min(start??index,index),b=Math.max(start??index,index),x=current.chart.timeScale().timeToCoordinate(rows[a].time)??0,end=current.chart.timeScale().timeToCoordinate(rows[b].time)??x;picker.querySelector('.replay-boundary').style.left=x+'px';const shade=picker.querySelector('.replay-future');shade.style.left=x+'px';shade.style.width=start!==null&&b>a?Math.max(2,end-x)+'px':'calc(100% - '+x+'px)';const label=picker.querySelector('span');label.textContent=chartTime(rows[a].time,zone())+(b>a?' → '+chartTime(rows[b].time,zone()):' · Начать здесь');label.style.left=Math.max(6,Math.min(x+8,entry.host.clientWidth-310))+'px';finish=b;}
  function choose(){const a=Math.min(start??index,index),last=start!==null&&Math.abs(start-index)>1?rows[finish].time:undefined;cancelPick();current.startReplay(rows[a].time,last);update();}
  picker.onpointermove=e=>{index=point(e);paint();};picker.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();index=point(e);start=index;picker.setPointerCapture(e.pointerId);paint();};picker.onpointerup=e=>{e.preventDefault();e.stopPropagation();index=point(e);paint();choose();};picker.onpointercancel=()=>{start=null;};picker.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Enter','Escape'].includes(e.key)){e.preventDefault();e.stopPropagation();if(e.key==='Escape'){cancelPick();return;}if(e.key==='Enter'){choose();return;}index=Math.max(0,Math.min(rows.length-1,index+(e.key==='ArrowLeft'?-1:1)));paint();}};
  const escape=e=>{if(e.key==='Escape'){e.preventDefault();cancelPick();}};document.addEventListener('keydown',escape);cleanup=()=>document.removeEventListener('keydown',escape);bar.querySelector('[data-replay=pick]').setAttribute('aria-pressed','true');paint();picker.focus();
 }
 bar.querySelector('form').onsubmit=e=>{e.preventDefault();cancelPick();const rows=api()?.getSourceRows()||[],row=rows.find(r=>day(r.time)>=field.value);if(!row||!api()?.startReplay(row.time))status.textContent='За этой датой нет загруженных свечей. Выберите другую дату.';};
 bar.onclick=e=>{const action=e.target.closest('[data-replay]')?.dataset.replay,current=api();if(action==='pick')pick();if(action==='play'){if(current?.getReplay().playing)current.pauseReplay();else current?.playReplay();}if(action==='step'||action==='back'){current?.pauseReplay();current?.stepReplay(action==='step'?1:-1);}if(action==='close'){cancelPick();current?.stopReplay();bar.hidden=true;button.setAttribute('aria-pressed','false');onStop();button.focus();}};
 bar.querySelector('[data-replay-speed]').onchange=e=>api()?.setReplaySpeed(Number(e.target.value));
 document.addEventListener('visibilitychange',()=>{if(document.hidden)api()?.pauseReplay();});window.addEventListener('pagehide',()=>api()?.pauseReplay());
 return {update,toggle(){if(!bar.hidden){cancelPick();api()?.stopReplay();bar.hidden=true;onStop();update();}else pick();},selection(){const current=api();if(previous&&previous!==current){cancelPick();previous.pauseReplay();field.value='';bar.hidden=!current?.getReplay().active;}previous=current;update();},pause(){cancelPick();api()?.pauseReplay();}};
}
