export function initReplayControls({main,button,activeChart,onStop=()=>{}}){
 const bar=document.createElement('section');bar.className='terminal-replay-bar';bar.hidden=true;bar.setAttribute('aria-label','Воспроизведение истории');
 bar.innerHTML='<form class="terminal-replay-date"><label>Начать с даты<input type="date" name="replayDate" required aria-label="Дата начала воспроизведения"></label><button type="submit">Начать</button></form><div class="terminal-replay-actions"><button type="button" data-replay="back" aria-label="Предыдущая свеча"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m14 5-7 7 7 7M7 12h14"/></svg></button><button type="button" data-replay="play">Воспроизвести</button><button type="button" data-replay="step" aria-label="Следующая свеча"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m10 5 7 7-7 7M3 12h14"/></svg></button><label>Скорость<select data-replay-speed aria-label="Скорость воспроизведения"><option value="0.5">0,5 свечи/с</option><option value="1" selected>1 свеча/с</option><option value="2">2 свечи/с</option><option value="5">5 свечей/с</option><option value="10">10 свечей/с</option></select></label><button type="button" data-replay="close">Выйти</button></div><output class="terminal-replay-status" role="status"></output><small>Воспроизводится выбранный график. Котировки и другие панели показывают последний снимок источника.</small>';
 main.querySelector('.terminal-grid').before(bar);let previous=null;
 const api=()=>activeChart()?.api,field=bar.querySelector('[name=replayDate]'),status=bar.querySelector('output');
 function update(){const current=api(),s=current?.getReplay()||{active:false};button.setAttribute('aria-pressed',String(!bar.hidden));if(s.speed)bar.querySelector('[data-replay-speed]').value=String(s.speed);
  bar.querySelector('[data-replay=play]').textContent=s.playing?'Пауза':'Воспроизвести';bar.querySelector('[data-replay=play]').disabled=!s.active||s.index>=s.total-1;bar.querySelector('[data-replay=step]').disabled=!s.active||s.index>=s.total-1;bar.querySelector('[data-replay=back]').disabled=!s.active||s.index===0;
  if(s.active){bar.hidden=false;bar.dataset.time=s.time;bar.dataset.count=s.index+1;status.textContent=new Date(s.time*1000).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})+' · свеча '+(s.index+1)+' из '+s.total+(s.index===s.total-1?' · Конец истории':'');}
  else {delete bar.dataset.time;delete bar.dataset.count;status.textContent=current?'Выберите дату начала. Будущие свечи появятся по шагам.':'Дождитесь загрузки свечей.';}
  const rows=activeChart()?.rows||[];bar.querySelector('[type=submit]').disabled=rows.length<2;if(rows.length){field.min=new Date(rows[0].time*1000).toLocaleDateString('en-CA',{timeZone:'Europe/Moscow'});field.max=new Date(rows.at(-1).time*1000).toLocaleDateString('en-CA',{timeZone:'Europe/Moscow'});if(!field.value||field.value<field.min||field.value>field.max)field.value=new Date(rows[Math.floor((rows.length-1)*.7)].time*1000).toLocaleDateString('en-CA',{timeZone:'Europe/Moscow'});}
 }
 bar.querySelector('form').onsubmit=e=>{e.preventDefault();const rows=activeChart()?.rows||[],day=Date.parse(field.value+'T00:00:00+03:00')/1000,time=Math.max(day,rows[0]?.time||day);if(!api()?.startReplay(time))status.textContent='За этой датой нет загруженных свечей. Выберите другую дату или загрузите историю.';};
 bar.onclick=e=>{const action=e.target.closest('[data-replay]')?.dataset.replay,current=api();if(!action)return;
  if(action==='play'){if(current?.getReplay().playing)current.pauseReplay();else current?.playReplay();}
  if(action==='step'||action==='back'){current?.pauseReplay();current?.stepReplay(action==='step'?1:-1);}
  if(action==='close'){current?.stopReplay();bar.hidden=true;button.setAttribute('aria-pressed','false');onStop();button.focus();}
 };
 bar.querySelector('[data-replay-speed]').onchange=e=>api()?.setReplaySpeed(Number(e.target.value));
 document.addEventListener('visibilitychange',()=>{if(document.hidden)api()?.pauseReplay();});window.addEventListener('pagehide',()=>api()?.pauseReplay());
 return {update,toggle(){if(!bar.hidden){api()?.stopReplay();bar.hidden=true;onStop();}else bar.hidden=false;update();},selection(){const current=api();if(previous&&previous!==current)previous.pauseReplay();if(current!==previous){if(previous)field.value='';bar.hidden=!current?.getReplay().active;}previous=current;update();},pause(){api()?.pauseReplay();}};
}
